### ISSUE TITLE
Setup Readme.md

### ISSUE THREAD

**Issue by PHAGUN-JAIN** [PHAGUN-JAIN/Algorithms#1]

**Comment by PHAGUN-JAIN** [comment]
Let's Start

**Comment by AkshatGoyal1018** [comment]
Should we use html?

**Comment by AkshatGoyal1018** [comment]
with css?

**Comment by PHAGUN-JAIN** [comment]
yass! but in what scope?

**Comment by AkshatGoyal1018** [comment]
Lets's leave that for later. First work up on rest of the issues.

**Comment by AkshatGoyal1018** [comment]
Write a basic readme.md for time being. we will upgrade it with time.

**Comment by PHAGUN-JAIN** [comment]
NOICE WORK! @AkshatGoyal1018  :)
